/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApartamentaiRouteImport } from './routes/apartamentai'
import { Route as ApieRouteImport } from './routes/apie'
import { Route as BanketineSaleRouteImport } from './routes/banketine-sale'
import { Route as DovanuKuponaiRouteImport } from './routes/dovanu-kuponai'
import { Route as KontaktaiRouteImport } from './routes/kontaktai'
import { Route as NamelisRouteImport } from './routes/namelis'
import { Route as PrivatumoPolitikaRouteImport } from './routes/privatumo-politika'
import { Route as RenginiaiRouteImport } from './routes/renginiai'
import { Route as RestobarasRouteImport } from './routes/restobaras'
import { Route as RestoranasRouteImport } from './routes/restoranas'
import { Route as SaunaRouteImport } from './routes/sauna'
import { Route as SpaRouteImport } from './routes/spa'
import { Route as TaisyklesRouteImport } from './routes/taisykles'
import { Route as ApartamentaiIndexRouteImport } from './routes/apartamentai.index'
import { Route as ApartamentaiPropertyIdRouteImport } from './routes/apartamentai.$propertyId'
import { Route as ApartamentaiStandartiniaiRouteImport } from './routes/apartamentai.standartiniai'
import { Route as ApartamentaiSuTerasaRouteImport } from './routes/apartamentai.su-terasa'
import { Route as ApieIndexRouteImport } from './routes/apie.index'
import { Route as ApieTaisyklesRouteImport } from './routes/apie.taisykles'
import { Route as RezervacijaPatvirtintaRouteImport } from './routes/rezervacija.patvirtinta'
import { Route as ApartamentaiTipasCategorySlugRouteImport } from './routes/apartamentai.tipas.$categorySlug'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApartamentaiRoute = ApartamentaiRouteImport.update({
  id: '/apartamentai',
  path: '/apartamentai',
  getParentRoute: () => rootRouteImport,
} as any)
const ApieRoute = ApieRouteImport.update({
  id: '/apie',
  path: '/apie',
  getParentRoute: () => rootRouteImport,
} as any)
const BanketineSaleRoute = BanketineSaleRouteImport.update({
  id: '/banketine-sale',
  path: '/banketine-sale',
  getParentRoute: () => rootRouteImport,
} as any)
const DovanuKuponaiRoute = DovanuKuponaiRouteImport.update({
  id: '/dovanu-kuponai',
  path: '/dovanu-kuponai',
  getParentRoute: () => rootRouteImport,
} as any)
const KontaktaiRoute = KontaktaiRouteImport.update({
  id: '/kontaktai',
  path: '/kontaktai',
  getParentRoute: () => rootRouteImport,
} as any)
const NamelisRoute = NamelisRouteImport.update({
  id: '/namelis',
  path: '/namelis',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivatumoPolitikaRoute = PrivatumoPolitikaRouteImport.update({
  id: '/privatumo-politika',
  path: '/privatumo-politika',
  getParentRoute: () => rootRouteImport,
} as any)
const RenginiaiRoute = RenginiaiRouteImport.update({
  id: '/renginiai',
  path: '/renginiai',
  getParentRoute: () => rootRouteImport,
} as any)
const RestobarasRoute = RestobarasRouteImport.update({
  id: '/restobaras',
  path: '/restobaras',
  getParentRoute: () => rootRouteImport,
} as any)
const RestoranasRoute = RestoranasRouteImport.update({
  id: '/restoranas',
  path: '/restoranas',
  getParentRoute: () => rootRouteImport,
} as any)
const SaunaRoute = SaunaRouteImport.update({
  id: '/sauna',
  path: '/sauna',
  getParentRoute: () => rootRouteImport,
} as any)
const SpaRoute = SpaRouteImport.update({
  id: '/spa',
  path: '/spa',
  getParentRoute: () => rootRouteImport,
} as any)
const TaisyklesRoute = TaisyklesRouteImport.update({
  id: '/taisykles',
  path: '/taisykles',
  getParentRoute: () => rootRouteImport,
} as any)
const ApartamentaiIndexRoute = ApartamentaiIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ApartamentaiRoute,
} as any)
const ApartamentaiPropertyIdRoute = ApartamentaiPropertyIdRouteImport.update({
  id: '/$propertyId',
  path: '/$propertyId',
  getParentRoute: () => ApartamentaiRoute,
} as any)
const ApartamentaiStandartiniaiRoute =
  ApartamentaiStandartiniaiRouteImport.update({
    id: '/standartiniai',
    path: '/standartiniai',
    getParentRoute: () => ApartamentaiRoute,
  } as any)
const ApartamentaiSuTerasaRoute = ApartamentaiSuTerasaRouteImport.update({
  id: '/su-terasa',
  path: '/su-terasa',
  getParentRoute: () => ApartamentaiRoute,
} as any)
const ApieIndexRoute = ApieIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ApieRoute,
} as any)
const ApieTaisyklesRoute = ApieTaisyklesRouteImport.update({
  id: '/taisykles',
  path: '/taisykles',
  getParentRoute: () => ApieRoute,
} as any)
const RezervacijaPatvirtintaRoute = RezervacijaPatvirtintaRouteImport.update({
  id: '/rezervacija/patvirtinta',
  path: '/rezervacija/patvirtinta',
  getParentRoute: () => rootRouteImport,
} as any)
const ApartamentaiTipasCategorySlugRoute =
  ApartamentaiTipasCategorySlugRouteImport.update({
    id: '/tipas/$categorySlug',
    path: '/tipas/$categorySlug',
    getParentRoute: () => ApartamentaiRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/apartamentai': typeof ApartamentaiRouteWithChildren
  '/apie': typeof ApieRouteWithChildren
  '/banketine-sale': typeof BanketineSaleRoute
  '/dovanu-kuponai': typeof DovanuKuponaiRoute
  '/kontaktai': typeof KontaktaiRoute
  '/namelis': typeof NamelisRoute
  '/privatumo-politika': typeof PrivatumoPolitikaRoute
  '/renginiai': typeof RenginiaiRoute
  '/restobaras': typeof RestobarasRoute
  '/restoranas': typeof RestoranasRoute
  '/sauna': typeof SaunaRoute
  '/spa': typeof SpaRoute
  '/taisykles': typeof TaisyklesRoute
  '/apartamentai/$propertyId': typeof ApartamentaiPropertyIdRoute
  '/apartamentai/standartiniai': typeof ApartamentaiStandartiniaiRoute
  '/apartamentai/su-terasa': typeof ApartamentaiSuTerasaRoute
  '/apie/taisykles': typeof ApieTaisyklesRoute
  '/rezervacija/patvirtinta': typeof RezervacijaPatvirtintaRoute
  '/apartamentai/': typeof ApartamentaiIndexRoute
  '/apie/': typeof ApieIndexRoute
  '/apartamentai/tipas/$categorySlug': typeof ApartamentaiTipasCategorySlugRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/banketine-sale': typeof BanketineSaleRoute
  '/dovanu-kuponai': typeof DovanuKuponaiRoute
  '/kontaktai': typeof KontaktaiRoute
  '/namelis': typeof NamelisRoute
  '/privatumo-politika': typeof PrivatumoPolitikaRoute
  '/renginiai': typeof RenginiaiRoute
  '/restobaras': typeof RestobarasRoute
  '/restoranas': typeof RestoranasRoute
  '/sauna': typeof SaunaRoute
  '/spa': typeof SpaRoute
  '/taisykles': typeof TaisyklesRoute
  '/apartamentai/$propertyId': typeof ApartamentaiPropertyIdRoute
  '/apartamentai/standartiniai': typeof ApartamentaiStandartiniaiRoute
  '/apartamentai/su-terasa': typeof ApartamentaiSuTerasaRoute
  '/apie/taisykles': typeof ApieTaisyklesRoute
  '/rezervacija/patvirtinta': typeof RezervacijaPatvirtintaRoute
  '/apartamentai': typeof ApartamentaiIndexRoute
  '/apie': typeof ApieIndexRoute
  '/apartamentai/tipas/$categorySlug': typeof ApartamentaiTipasCategorySlugRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/apartamentai': typeof ApartamentaiRouteWithChildren
  '/apie': typeof ApieRouteWithChildren
  '/banketine-sale': typeof BanketineSaleRoute
  '/dovanu-kuponai': typeof DovanuKuponaiRoute
  '/kontaktai': typeof KontaktaiRoute
  '/namelis': typeof NamelisRoute
  '/privatumo-politika': typeof PrivatumoPolitikaRoute
  '/renginiai': typeof RenginiaiRoute
  '/restobaras': typeof RestobarasRoute
  '/restoranas': typeof RestoranasRoute
  '/sauna': typeof SaunaRoute
  '/spa': typeof SpaRoute
  '/taisykles': typeof TaisyklesRoute
  '/apartamentai/$propertyId': typeof ApartamentaiPropertyIdRoute
  '/apartamentai/standartiniai': typeof ApartamentaiStandartiniaiRoute
  '/apartamentai/su-terasa': typeof ApartamentaiSuTerasaRoute
  '/apie/taisykles': typeof ApieTaisyklesRoute
  '/rezervacija/patvirtinta': typeof RezervacijaPatvirtintaRoute
  '/apartamentai/': typeof ApartamentaiIndexRoute
  '/apie/': typeof ApieIndexRoute
  '/apartamentai/tipas/$categorySlug': typeof ApartamentaiTipasCategorySlugRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/apartamentai'
    | '/apie'
    | '/banketine-sale'
    | '/dovanu-kuponai'
    | '/kontaktai'
    | '/namelis'
    | '/privatumo-politika'
    | '/renginiai'
    | '/restobaras'
    | '/restoranas'
    | '/sauna'
    | '/spa'
    | '/taisykles'
    | '/apartamentai/$propertyId'
    | '/apartamentai/standartiniai'
    | '/apartamentai/su-terasa'
    | '/apie/taisykles'
    | '/rezervacija/patvirtinta'
    | '/apartamentai/'
    | '/apie/'
    | '/apartamentai/tipas/$categorySlug'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/banketine-sale'
    | '/dovanu-kuponai'
    | '/kontaktai'
    | '/namelis'
    | '/privatumo-politika'
    | '/renginiai'
    | '/restobaras'
    | '/restoranas'
    | '/sauna'
    | '/spa'
    | '/taisykles'
    | '/apartamentai/$propertyId'
    | '/apartamentai/standartiniai'
    | '/apartamentai/su-terasa'
    | '/apie/taisykles'
    | '/rezervacija/patvirtinta'
    | '/apartamentai'
    | '/apie'
    | '/apartamentai/tipas/$categorySlug'
  id:
    | '__root__'
    | '/'
    | '/apartamentai'
    | '/apie'
    | '/banketine-sale'
    | '/dovanu-kuponai'
    | '/kontaktai'
    | '/namelis'
    | '/privatumo-politika'
    | '/renginiai'
    | '/restobaras'
    | '/restoranas'
    | '/sauna'
    | '/spa'
    | '/taisykles'
    | '/apartamentai/$propertyId'
    | '/apartamentai/standartiniai'
    | '/apartamentai/su-terasa'
    | '/apie/taisykles'
    | '/rezervacija/patvirtinta'
    | '/apartamentai/'
    | '/apie/'
    | '/apartamentai/tipas/$categorySlug'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ApartamentaiRoute: typeof ApartamentaiRouteWithChildren
  ApieRoute: typeof ApieRouteWithChildren
  BanketineSaleRoute: typeof BanketineSaleRoute
  DovanuKuponaiRoute: typeof DovanuKuponaiRoute
  KontaktaiRoute: typeof KontaktaiRoute
  NamelisRoute: typeof NamelisRoute
  PrivatumoPolitikaRoute: typeof PrivatumoPolitikaRoute
  RenginiaiRoute: typeof RenginiaiRoute
  RestobarasRoute: typeof RestobarasRoute
  RestoranasRoute: typeof RestoranasRoute
  SaunaRoute: typeof SaunaRoute
  SpaRoute: typeof SpaRoute
  TaisyklesRoute: typeof TaisyklesRoute
  RezervacijaPatvirtintaRoute: typeof RezervacijaPatvirtintaRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/apartamentai': {
      id: '/apartamentai'
      path: '/apartamentai'
      fullPath: '/apartamentai'
      preLoaderRoute: typeof ApartamentaiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/apie': {
      id: '/apie'
      path: '/apie'
      fullPath: '/apie'
      preLoaderRoute: typeof ApieRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/banketine-sale': {
      id: '/banketine-sale'
      path: '/banketine-sale'
      fullPath: '/banketine-sale'
      preLoaderRoute: typeof BanketineSaleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dovanu-kuponai': {
      id: '/dovanu-kuponai'
      path: '/dovanu-kuponai'
      fullPath: '/dovanu-kuponai'
      preLoaderRoute: typeof DovanuKuponaiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kontaktai': {
      id: '/kontaktai'
      path: '/kontaktai'
      fullPath: '/kontaktai'
      preLoaderRoute: typeof KontaktaiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/namelis': {
      id: '/namelis'
      path: '/namelis'
      fullPath: '/namelis'
      preLoaderRoute: typeof NamelisRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privatumo-politika': {
      id: '/privatumo-politika'
      path: '/privatumo-politika'
      fullPath: '/privatumo-politika'
      preLoaderRoute: typeof PrivatumoPolitikaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/renginiai': {
      id: '/renginiai'
      path: '/renginiai'
      fullPath: '/renginiai'
      preLoaderRoute: typeof RenginiaiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/restobaras': {
      id: '/restobaras'
      path: '/restobaras'
      fullPath: '/restobaras'
      preLoaderRoute: typeof RestobarasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/restoranas': {
      id: '/restoranas'
      path: '/restoranas'
      fullPath: '/restoranas'
      preLoaderRoute: typeof RestoranasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sauna': {
      id: '/sauna'
      path: '/sauna'
      fullPath: '/sauna'
      preLoaderRoute: typeof SaunaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/spa': {
      id: '/spa'
      path: '/spa'
      fullPath: '/spa'
      preLoaderRoute: typeof SpaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/taisykles': {
      id: '/taisykles'
      path: '/taisykles'
      fullPath: '/taisykles'
      preLoaderRoute: typeof TaisyklesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/apartamentai/': {
      id: '/apartamentai/'
      path: '/'
      fullPath: '/apartamentai/'
      preLoaderRoute: typeof ApartamentaiIndexRouteImport
      parentRoute: typeof ApartamentaiRoute
    }
    '/apartamentai/$propertyId': {
      id: '/apartamentai/$propertyId'
      path: '/$propertyId'
      fullPath: '/apartamentai/$propertyId'
      preLoaderRoute: typeof ApartamentaiPropertyIdRouteImport
      parentRoute: typeof ApartamentaiRoute
    }
    '/apartamentai/standartiniai': {
      id: '/apartamentai/standartiniai'
      path: '/standartiniai'
      fullPath: '/apartamentai/standartiniai'
      preLoaderRoute: typeof ApartamentaiStandartiniaiRouteImport
      parentRoute: typeof ApartamentaiRoute
    }
    '/apartamentai/su-terasa': {
      id: '/apartamentai/su-terasa'
      path: '/su-terasa'
      fullPath: '/apartamentai/su-terasa'
      preLoaderRoute: typeof ApartamentaiSuTerasaRouteImport
      parentRoute: typeof ApartamentaiRoute
    }
    '/apie/': {
      id: '/apie/'
      path: '/'
      fullPath: '/apie/'
      preLoaderRoute: typeof ApieIndexRouteImport
      parentRoute: typeof ApieRoute
    }
    '/apie/taisykles': {
      id: '/apie/taisykles'
      path: '/taisykles'
      fullPath: '/apie/taisykles'
      preLoaderRoute: typeof ApieTaisyklesRouteImport
      parentRoute: typeof ApieRoute
    }
    '/rezervacija/patvirtinta': {
      id: '/rezervacija/patvirtinta'
      path: '/rezervacija/patvirtinta'
      fullPath: '/rezervacija/patvirtinta'
      preLoaderRoute: typeof RezervacijaPatvirtintaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/apartamentai/tipas/$categorySlug': {
      id: '/apartamentai/tipas/$categorySlug'
      path: '/tipas/$categorySlug'
      fullPath: '/apartamentai/tipas/$categorySlug'
      preLoaderRoute: typeof ApartamentaiTipasCategorySlugRouteImport
      parentRoute: typeof ApartamentaiRoute
    }
  }
}

interface ApartamentaiRouteChildren {
  ApartamentaiPropertyIdRoute: typeof ApartamentaiPropertyIdRoute
  ApartamentaiStandartiniaiRoute: typeof ApartamentaiStandartiniaiRoute
  ApartamentaiSuTerasaRoute: typeof ApartamentaiSuTerasaRoute
  ApartamentaiIndexRoute: typeof ApartamentaiIndexRoute
  ApartamentaiTipasCategorySlugRoute: typeof ApartamentaiTipasCategorySlugRoute
}

const ApartamentaiRouteChildren: ApartamentaiRouteChildren = {
  ApartamentaiPropertyIdRoute: ApartamentaiPropertyIdRoute,
  ApartamentaiStandartiniaiRoute: ApartamentaiStandartiniaiRoute,
  ApartamentaiSuTerasaRoute: ApartamentaiSuTerasaRoute,
  ApartamentaiIndexRoute: ApartamentaiIndexRoute,
  ApartamentaiTipasCategorySlugRoute: ApartamentaiTipasCategorySlugRoute,
}

const ApartamentaiRouteWithChildren = ApartamentaiRoute._addFileChildren(
  ApartamentaiRouteChildren,
)

interface ApieRouteChildren {
  ApieTaisyklesRoute: typeof ApieTaisyklesRoute
  ApieIndexRoute: typeof ApieIndexRoute
}

const ApieRouteChildren: ApieRouteChildren = {
  ApieTaisyklesRoute: ApieTaisyklesRoute,
  ApieIndexRoute: ApieIndexRoute,
}

const ApieRouteWithChildren = ApieRoute._addFileChildren(ApieRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ApartamentaiRoute: ApartamentaiRouteWithChildren,
  ApieRoute: ApieRouteWithChildren,
  BanketineSaleRoute: BanketineSaleRoute,
  DovanuKuponaiRoute: DovanuKuponaiRoute,
  KontaktaiRoute: KontaktaiRoute,
  NamelisRoute: NamelisRoute,
  PrivatumoPolitikaRoute: PrivatumoPolitikaRoute,
  RenginiaiRoute: RenginiaiRoute,
  RestobarasRoute: RestobarasRoute,
  RestoranasRoute: RestoranasRoute,
  SaunaRoute: SaunaRoute,
  SpaRoute: SpaRoute,
  TaisyklesRoute: TaisyklesRoute,
  RezervacijaPatvirtintaRoute: RezervacijaPatvirtintaRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
